-- Add quote, speaker, and expanded_summary columns to snips table
-- These fields are generated by the snip and enhance-snip edge functions
ALTER TABLE snips
  ADD COLUMN IF NOT EXISTS quote TEXT,
  ADD COLUMN IF NOT EXISTS speaker TEXT,
  ADD COLUMN IF NOT EXISTS expanded_summary TEXT;
